name: Build and push docker image
on:
  push:
    branches: [ master ]
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: kanareklife/woklearner-frontend
          tag: latest 
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
